import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from '@tanstack/react-router';
import { toast } from 'sonner';
import { Send } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input, Field } from '@/components/bond/field';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { useAuth } from '@/lib/auth/use-auth';
import { supabase } from '@/integrations/supabase/client';
import { date, STATUS_LABELS, rememberAccess } from '@/lib/platform/data';

export function RequestProduct({product}:{product:{id:string;name:string}}) {
 const {user}=useAuth();const qc=useQueryClient();const [open,setOpen]=useState(false);const [quantity,setQuantity]=useState('1');const [unit,setUnit]=useState('unidade');const [notes,setNotes]=useState('');const [busy,setBusy]=useState(false);
 if(!user)return <Button asChild variant="outline" className="mt-5"><Link to="/login" onClick={()=>rememberAccess('cliente')}>Entrar para solicitar <Send/></Link></Button>;
 return <><Button variant="outline" className="mt-5" onClick={()=>setOpen(true)}>Solicitar produto <Send/></Button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Solicitar {product.name}</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);const {error}=await supabase.from('product_requests').insert({user_id:user.id,product_id:product.id,quantity:Number(quantity),unit,notes:notes||null});setBusy(false);if(error){toast.error('Não foi possível enviar a solicitação.');return;}await qc.invalidateQueries({queryKey:['product-requests']});await qc.invalidateQueries({queryKey:['platform-snapshot']});toast.success('Solicitação registrada para a equipe comercial.');setOpen(false);setNotes('');}}><Field htmlFor={`quantity-${product.id}`} label="Quantidade"><Input id={`quantity-${product.id}`} type="number" min="0.01" step="0.01" required value={quantity} onChange={e=>setQuantity(e.target.value)}/></Field><Field htmlFor={`unit-${product.id}`} label="Unidade"><select id={`unit-${product.id}`} className="h-11 w-full rounded-md border border-border bg-card px-3" value={unit} onChange={e=>setUnit(e.target.value)}>{['unidade','litro','kg'].map(u=><option key={u}>{u}</option>)}</select></Field><Field htmlFor={`notes-${product.id}`} label="Observações"><Input id={`notes-${product.id}`} value={notes} onChange={e=>setNotes(e.target.value)} maxLength={2000}/></Field><Button type="submit" disabled={busy}>{busy?'Enviando…':'Enviar solicitação'}<Send/></Button></form></DialogContent></Dialog></>;
}
export function MyRequests(){const {user}=useAuth();const q=useQuery({queryKey:['product-requests',user?.id],enabled:Boolean(user),queryFn:async()=>{const {data,error}=await supabase.from('product_requests').select('id,quantity,unit,notes,status,created_at,products(name)').eq('user_id',user?.id??'').order('created_at',{ascending:false});if(error)throw error;return data;}});return <section className="mt-10 border-t border-border pt-7"><h2 className="text-xl font-bold">Minhas solicitações</h2>{q.isPending?<p className="mt-5 text-sm text-steel">Carregando…</p>:q.isError?<p className="mt-5 text-sm text-destructive">Não foi possível consultar suas solicitações.</p>:q.data.length===0?<p className="mt-5 text-sm text-steel">Você ainda não enviou solicitações.</p>:<div className="mt-4 divide-y divide-border">{q.data.map(r=><article key={r.id} className="flex flex-wrap justify-between gap-4 py-5"><div><h3 className="font-semibold">{r.products?.name??'Produto'}</h3><p className="mt-1 text-sm text-steel">{r.quantity} {r.unit} · {date(r.created_at)}</p>{r.notes?<p className="mt-2 text-sm text-steel">{r.notes}</p>:null}</div><span className="text-sm text-aqua">{STATUS_LABELS[r.status]}</span></article>)}</div>}</section>}