import { useState,type ReactNode } from 'react';
import { Link,useNavigate } from '@tanstack/react-router';
import { useQueryClient } from '@tanstack/react-query';
import { Menu,X,LogOut,ArrowUpRight,ShieldCheck,LayoutDashboard,Building2,BriefcaseBusiness,UserRound,CreditCard } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ThemeToggle } from '@/lib/theme';
import { useAuth } from '@/lib/auth/use-auth';
import { supabase } from '@/integrations/supabase/client';
export function PlatformShell({title,children}:{title:string;children:ReactNode}){const [open,setOpen]=useState(false);const {role,fullName}=useAuth();const qc=useQueryClient();const navigate=useNavigate();return <div className="min-h-screen bg-background lg:grid lg:grid-cols-[240px_1fr]"><aside className={`${open?'flex':'hidden'} fixed inset-0 z-50 flex-col border-r border-border bg-card p-5 lg:sticky lg:top-0 lg:flex lg:h-screen`}><div className="flex items-center justify-between"><Link to="/" className="flex items-center gap-2 font-display font-bold"><img src="/icons/icon-192.png" alt="" className="size-8 rounded-md"/>Bondmann</Link><Button size="icon" variant="ghost" className="lg:hidden" onClick={()=>setOpen(false)} aria-label="Fechar menu"><X/></Button></div><p className="mt-4 text-xs uppercase text-steel">Commercial Hub</p><nav className="mt-8 space-y-2">{role==='admin'?<><Nav to="/administracao" label="Administração" Icon={ShieldCheck}/><Nav to="/painel" label="Hub comercial" Icon={LayoutDashboard}/><Nav to="/cliente" label="Área do cliente" Icon={UserRound}/><Nav to="/representante" label="Representante" Icon={BriefcaseBusiness}/><Nav to="/empresa-painel" label="Área empresarial" Icon={Building2}/><Nav to="/funcionario" label="Funcionário" Icon={UserRound}/></>:null}<Nav to="/planos" label="Planos" Icon={CreditCard}/><Nav to="/assinatura" label="Minha assinatura" Icon={CreditCard}/></nav><div className="mt-auto border-t border-border pt-5"><p className="text-sm font-semibold">{fullName??'Minha conta'}</p><Button variant="ghost" className="mt-3" onClick={async()=>{await qc.cancelQueries();qc.clear();await supabase.auth.signOut();void navigate({to:'/login',replace:true})}}><LogOut/> Sair</Button></div></aside><div className="min-w-0"><header className="flex min-h-20 flex-wrap items-center justify-between gap-3 border-b border-border px-5 lg:px-9"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Abrir menu" onClick={()=>setOpen(true)}><Menu/></Button><span className="text-sm font-semibold">{title}</span></div><div className="flex items-center gap-3"><ThemeToggle/><Link to="/" className="text-xs text-aqua">Ver site <ArrowUpRight className="inline size-3"/></Link></div></header><main className="mx-auto max-w-7xl px-5 py-9 lg:px-9">{role==='admin'?<p className="mb-6 flex items-center gap-2 border-b border-border pb-4 text-xs font-medium text-aqua"><ShieldCheck className="size-4"/> Administrador da plataforma · Acesso irrestrito</p>:null}{children}</main></div></div>}
function Nav({to,label,Icon}:{to:'/administracao'|'/painel'|'/cliente'|'/representante'|'/empresa-painel'|'/funcionario'|'/planos'|'/assinatura';label:string;Icon:typeof Menu}){return <Link to={to} search={to==='/painel'?{modulo:'Dashboard'}:{}} className="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm text-steel hover:bg-secondary hover:text-foreground"><Icon className="size-4"/>{label}</Link>}
export function Title({eyebrow,title}:{eyebrow:string;title:string}){return <><p className="text-xs font-semibold uppercase text-aqua">{eyebrow}</p><h1 className="mt-3 text-3xl font-bold">{title}</h1></>}
export function Empty({title,text}:{title:string;text:string}){return <div className="border-y border-border py-12"><h2 className="text-xl font-bold">{title}</h2><p className="mt-3 max-w-xl text-sm text-steel">{text}</p></div>}
