import { useEffect, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowRight, ArrowUpRight, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/bond/field';
import { SiteShell, PageIntro } from './site-layout';
import { SEGMENTS, SITE, PLACEHOLDER } from '@/lib/site-config';
import { supabase } from '@/integrations/supabase/client';
import agro from '@/assets/segmento-agro.jpg';
import metal from '@/assets/segmento-metalurgia.jpg';
import agua from '@/assets/segmento-agua.jpg';
import industrial from '@/assets/bondmann-industrial.jpg';

const images: Record<string,string> = { agro, metalurgia: metal, 'tratamento-agua': agua, industrial };
const actions = [{to:'/solucoes', label:'Conheça nossas soluções'}, {to:'/contato',label:'Fale conosco'}, {to:'/login',label:'Acessar área do cliente'}] as const;
export function HomePage(){return <SiteShell>
  <section className="relative mx-auto mt-3 min-h-[520px] max-w-[1500px] overflow-hidden md:min-h-[620px]">
    <img src={industrial} alt="Instalação industrial de produtos químicos" className="absolute inset-0 size-full object-cover" />
    <div className="absolute inset-0 bg-linear-to-r from-slateink via-slateink/75 to-transparent" />
    <div className="relative mx-auto flex min-h-[520px] max-w-6xl flex-col justify-center px-6 py-16 text-primary-foreground md:min-h-[620px]">
      <p className="mb-6 text-xs font-bold uppercase tracking-[.24em] text-primary-foreground/75">Química em movimento / Bondmann</p>
      <h1 className="max-w-2xl text-5xl leading-[1.08] font-bold sm:text-6xl md:text-7xl">Bondmann Química.<br/>Soluções para cada operação.</h1>
      <p className="mt-6 max-w-xl text-base leading-relaxed text-primary-foreground/85 md:text-lg">Explore segmentos, aplicações e produtos em um só lugar. Uma nova forma de encontrar caminhos para as necessidades da sua operação.</p>
      <div className="mt-9 flex flex-wrap gap-3">{actions.map((a,i)=><Button key={a.to} asChild variant={i===0?'signal':'glass'} className={i>0?'text-foreground':''}><Link to={a.to}>{a.label}<ArrowUpRight/></Link></Button>)}</div>
    </div>
  </section>
  <section className="mx-auto grid max-w-6xl gap-10 px-5 py-20 md:grid-cols-[.8fr_1.2fr] md:py-28"><div><p className="text-xs font-bold uppercase text-aqua">01 / Quem somos</p><h2 className="mt-4 text-3xl font-bold sm:text-4xl">Química conectada aos desafios de cada setor.</h2></div><div className="border-l-2 border-bond pl-6 text-lg leading-relaxed text-steel"><p>A Bondmann reúne soluções químicas organizadas para diferentes contextos de aplicação. Este espaço apresenta o portfólio e facilita o contato entre clientes e equipe comercial.</p><Button asChild variant="link" className="mt-5 px-0"><Link to="/empresa">Conheça a empresa <ArrowRight/></Link></Button></div></section>
  <section className="bg-secondary/65 py-20"><div className="mx-auto max-w-6xl px-5"><div className="mb-9 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase text-aqua">02 / Atuação</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Segmentos em foco</h2></div><Button asChild variant="outline"><Link to="/solucoes">Explorar soluções <ArrowRight/></Link></Button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{SEGMENTS.map((s,i)=><Link to="/solucoes" key={s.slug} className="group relative flex min-h-64 items-end overflow-hidden rounded-md bg-slateink p-6 text-primary-foreground">{images[s.slug] ? <img src={images[s.slug]} alt="" loading="lazy" className="absolute inset-0 size-full object-cover opacity-75 transition-transform duration-500 group-hover:scale-105"/>:null}<div className="absolute inset-0 bg-linear-to-t from-slateink via-slateink/15 to-transparent"/><div className="relative w-full"><span className="text-xs opacity-75">0{i+1} / SEGMENTO</span><div className="mt-2 flex items-center justify-between gap-3 text-xl font-bold">{s.name}<ArrowUpRight className="size-5 shrink-0"/></div></div></Link>)}</div></div></section>
  <section className="mx-auto max-w-6xl px-5 py-20"><p className="text-xs font-bold uppercase text-aqua">03 / Descubra</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Do desafio à aplicação.</h2><div className="mt-9 grid gap-4 md:grid-cols-3">{[['01','Produtos','Conheça os itens cadastrados no catálogo.','/produtos'],['02','Soluções','Navegue por segmentos e aplicações.','/solucoes'],['03','Serviços','Veja a estrutura de atendimento técnico e comercial.','/servicos']].map(([n,title,text,to])=><Link key={to} to={to as '/produtos'|'/solucoes'|'/servicos'} className="glass group rounded-md border border-border p-7"><span className="text-xs font-semibold text-aqua">{n} / BONDMANN</span><h3 className="mt-10 text-2xl font-bold">{title}</h3><p className="mt-3 text-sm text-steel">{text}</p><ArrowUpRight className="mt-8 size-5 text-aqua transition-transform group-hover:translate-x-1"/></Link>)}</div></section>
</SiteShell>}
export function CompanyPage(){return <SiteShell><PageIntro eyebrow="A Bondmann" title="Uma plataforma para conectar desafios a soluções." text="Conheça a estrutura comercial e explore os segmentos atendidos pelo catálogo Bondmann."/><div className="mx-auto grid max-w-6xl gap-10 px-4 pb-20 md:grid-cols-2"><img src={industrial} alt="Instalação industrial ilustrativa" className="h-80 w-full rounded-md object-cover"/><div className="self-center space-y-5 text-steel"><h2 className="text-2xl font-bold text-foreground">Uma visão integrada</h2><p>Produtos, aplicações e segmentos em uma experiência organizada para facilitar a consulta e o relacionamento comercial.</p><p>Informações institucionais oficiais adicionais serão incluídas quando disponibilizadas pela Bondmann.</p><Button asChild><Link to="/contato">Entre em contato <ArrowRight/></Link></Button></div></div></SiteShell>}
export function ServicesPage(){return <SiteShell><PageIntro eyebrow="Serviços" title="Atendimento orientado à sua operação." text="Conheça os caminhos de atendimento técnico e comercial da Bondmann. O detalhamento oficial dos serviços será publicado futuramente."/><div className="mx-auto grid max-w-6xl gap-4 px-4 pb-20 md:grid-cols-2">{[['Atendimento comercial','Converse com a equipe para conhecer o portfólio e encontrar informações sobre produtos.'],['Atendimento técnico','Solicite informações sobre aplicações e materiais disponíveis para avaliação.']].map(([title,desc])=><div key={title} className="glass rounded-md border border-border p-8"><span className="text-xs font-semibold uppercase text-aqua">Bondmann / Atendimento</span><h2 className="mt-8 text-2xl font-bold">{title}</h2><p className="mt-3 text-steel">{desc}</p><Button asChild variant="link" className="mt-5 px-0"><Link to="/contato">Consultar canais <ArrowRight/></Link></Button></div>)}</div></SiteShell>}
export function ContactPage(){return <SiteShell><PageIntro eyebrow="Contato" title="Vamos conversar sobre sua necessidade?" text="Os canais oficiais serão publicados aqui após confirmação pela Bondmann."/><div className="mx-auto grid max-w-6xl gap-4 px-4 pb-20 sm:grid-cols-2">{[['Telefone',SITE.phone],['WhatsApp',SITE.whatsapp],['E-mail',SITE.email],['Endereço',SITE.address],['Instagram',SITE.instagram],['LinkedIn',SITE.linkedin]].map(([label,value])=><div key={label} className="border-t border-border py-6"><p className="text-xs font-bold uppercase text-aqua">{label}</p><p className="mt-3 text-xl font-semibold">{value??PLACEHOLDER}</p></div>)}</div></SiteShell>}
type Product = {id:string; name:string; code:string|null; description:string|null; category:string|null; image_url:string|null; segment_id:string|null; features:string[]; datasheet_url:string|null};
type Segment = {id:string; name:string};
export function ProductsPage(){const [products,setProducts]=useState<Product[]>([]);const [segments,setSegments]=useState<Segment[]>([]);const [search,setSearch]=useState('');const [segment,setSegment]=useState('all');const [loading,setLoading]=useState(true);const [error,setError]=useState(false);
  useEffect(()=>{let active=true;Promise.all([supabase.from('products').select('id,name,code,description,category,image_url,segment_id,features,datasheet_url').eq('is_published',true).order('name'),supabase.from('segments').select('id,name').eq('is_active',true).order('sort_order')]).then(([p,s])=>{if(!active)return;setProducts(p.data??[]);setSegments(s.data??[]);setError(Boolean(p.error||s.error));setLoading(false)});return()=>{active=false}},[]);
  const shown=products.filter(p=>(segment==='all'||p.segment_id===segment)&&`${p.name} ${p.category??''} ${p.description??''}`.toLowerCase().includes(search.toLowerCase()));return <SiteShell><PageIntro eyebrow="Catálogo" title="Produtos Bondmann" text="Explore os produtos publicados e encontre informações por nome, categoria ou segmento."/><div className="mx-auto max-w-6xl px-4 pb-20"><div className="grid gap-3 border-y border-border py-5 sm:grid-cols-[1fr_220px]"><label className="relative"><Search className="absolute left-4 top-4 size-4 text-steel"/><Input aria-label="Pesquisar produtos" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar produtos" className="pl-11"/></label><select aria-label="Filtrar segmento" className="h-12 rounded-md border border-border bg-card px-4 text-sm" value={segment} onChange={e=>setSegment(e.target.value)}><option value="all">Todos os segmentos</option>{segments.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></div>{loading?<p className="py-16 text-center text-steel">Carregando catálogo…</p>:error?<p className="py-16 text-center text-steel">Não foi possível consultar o catálogo agora.</p>:shown.length===0?<div className="py-20 text-center"><h2 className="text-2xl font-bold">Nenhum produto encontrado</h2><p className="mt-2 text-steel">{products.length?'Tente outra busca ou segmento.':'Os produtos serão exibidos quando forem publicados no catálogo.'}</p></div>:<div className="grid gap-4 py-8 sm:grid-cols-2 lg:grid-cols-3">{shown.map(p=><article key={p.id} className="overflow-hidden rounded-md border border-border bg-card"><div className="flex h-48 items-center justify-center bg-secondary">{p.image_url?<img src={p.image_url} alt={p.name} loading="lazy" className="size-full object-cover"/>:<span className="text-xs font-bold uppercase text-steel">Bondmann / Produto</span>}</div><div className="p-6"><span className="text-xs font-semibold uppercase text-aqua">{segments.find(s=>s.id===p.segment_id)?.name??p.category??'Catálogo'}</span><h2 className="mt-3 text-xl font-bold">{p.name}</h2>{p.code?<p className="mt-1 text-xs text-steel">Código {p.code}</p>:null}<p className="mt-3 text-sm text-steel">{p.description??'Informações adicionais em atualização.'}</p>{p.features.length?<ul className="mt-4 list-inside list-disc text-sm text-steel">{p.features.map(f=><li key={f}>{f}</li>)}</ul>:null}{p.datasheet_url?<a href={p.datasheet_url} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex text-sm font-semibold text-aqua">Consultar ficha técnica <ArrowUpRight className="ml-1 size-4"/></a>:null}</div></article>)}</div>}</div></SiteShell>}
export function SolutionsPage(){return <SiteShell><PageIntro eyebrow="Soluções" title="Uma jornada da necessidade ao produto." text="A estrutura do catálogo conecta segmentos, aplicações e produtos. As recomendações específicas serão disponibilizadas quando validadas pela equipe."/><div className="mx-auto max-w-6xl px-4 pb-20"><div className="grid gap-3 md:grid-cols-4">{[['01','Problema','Identifique a necessidade da operação.'],['02','Aplicação','Defina o contexto de uso.'],['03','Solução','Explore o caminho adequado.'],['04','Produto','Consulte itens publicados.']].map(([n,t,d])=><div key={n} className="border-t-2 border-aqua py-6"><span className="text-xs text-aqua">{n} / ETAPA</span><h2 className="mt-7 text-xl font-bold">{t}</h2><p className="mt-2 text-sm text-steel">{d}</p></div>)}</div><h2 className="mt-16 text-2xl font-bold">Explore por segmento</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{SEGMENTS.map(s=><div key={s.slug} className="glass rounded-md border border-border p-6"><h3 className="text-lg font-bold">{s.name}</h3><p className="mt-2 text-sm text-steel">{s.text}</p><Button asChild variant="link" className="mt-3 px-0"><Link to="/produtos">Ver produtos <ArrowRight/></Link></Button></div>)}</div></div></SiteShell>}
