/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedClienteRouteImport } from './routes/_authenticated/cliente'
import { Route as AuthenticatedEmpresaPainelRouteImport } from './routes/_authenticated/empresa-painel'
import { Route as AuthenticatedFuncionarioRouteImport } from './routes/_authenticated/funcionario'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedRepresentanteRouteImport } from './routes/_authenticated/representante'
import { Route as AuthConfirmRouteImport } from './routes/auth_.confirm'
import { Route as AuthResetPasswordRouteImport } from './routes/auth_.reset-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClienteRoute = AuthenticatedClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresaPainelRoute =
  AuthenticatedEmpresaPainelRouteImport.update({
    id: '/empresa-painel',
    path: '/empresa-painel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFuncionarioRoute =
  AuthenticatedFuncionarioRouteImport.update({
    id: '/funcionario',
    path: '/funcionario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepresentanteRoute =
  AuthenticatedRepresentanteRouteImport.update({
    id: '/representante',
    path: '/representante',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth_/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth_/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/produtos': typeof ProdutosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/servicos': typeof ServicosRoute
  '/solucoes': typeof SolucoesRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/cliente': typeof AuthenticatedClienteRoute
  '/empresa-painel': typeof AuthenticatedEmpresaPainelRoute
  '/funcionario': typeof AuthenticatedFuncionarioRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/representante': typeof AuthenticatedRepresentanteRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/produtos': typeof ProdutosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/servicos': typeof ServicosRoute
  '/solucoes': typeof SolucoesRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/cliente': typeof AuthenticatedClienteRoute
  '/empresa-painel': typeof AuthenticatedEmpresaPainelRoute
  '/funcionario': typeof AuthenticatedFuncionarioRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/representante': typeof AuthenticatedRepresentanteRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/produtos': typeof ProdutosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/servicos': typeof ServicosRoute
  '/solucoes': typeof SolucoesRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/cliente': typeof AuthenticatedClienteRoute
  '/_authenticated/empresa-painel': typeof AuthenticatedEmpresaPainelRoute
  '/_authenticated/funcionario': typeof AuthenticatedFuncionarioRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/representante': typeof AuthenticatedRepresentanteRoute
  '/auth_/confirm': typeof AuthConfirmRoute
  '/auth_/reset-password': typeof AuthResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/contato'
    | '/empresa'
    | '/login'
    | '/planos'
    | '/produtos'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/servicos'
    | '/solucoes'
    | '/assinatura'
    | '/cliente'
    | '/empresa-painel'
    | '/funcionario'
    | '/painel'
    | '/representante'
    | '/auth/confirm'
    | '/auth/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/contato'
    | '/empresa'
    | '/login'
    | '/planos'
    | '/produtos'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/servicos'
    | '/solucoes'
    | '/assinatura'
    | '/cliente'
    | '/empresa-painel'
    | '/funcionario'
    | '/painel'
    | '/representante'
    | '/auth/confirm'
    | '/auth/reset-password'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cadastro'
    | '/contato'
    | '/empresa'
    | '/login'
    | '/planos'
    | '/produtos'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/servicos'
    | '/solucoes'
    | '/_authenticated/assinatura'
    | '/_authenticated/cliente'
    | '/_authenticated/empresa-painel'
    | '/_authenticated/funcionario'
    | '/_authenticated/painel'
    | '/_authenticated/representante'
    | '/auth_/confirm'
    | '/auth_/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CadastroRoute: typeof CadastroRoute
  ContatoRoute: typeof ContatoRoute
  EmpresaRoute: typeof EmpresaRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  ProdutosRoute: typeof ProdutosRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  ServicosRoute: typeof ServicosRoute
  SolucoesRoute: typeof SolucoesRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente': {
      id: '/_authenticated/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthenticatedClienteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa-painel': {
      id: '/_authenticated/empresa-painel'
      path: '/empresa-painel'
      fullPath: '/empresa-painel'
      preLoaderRoute: typeof AuthenticatedEmpresaPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcionario': {
      id: '/_authenticated/funcionario'
      path: '/funcionario'
      fullPath: '/funcionario'
      preLoaderRoute: typeof AuthenticatedFuncionarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/representante': {
      id: '/_authenticated/representante'
      path: '/representante'
      fullPath: '/representante'
      preLoaderRoute: typeof AuthenticatedRepresentanteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth_/confirm': {
      id: '/auth_/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/reset-password': {
      id: '/auth_/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedClienteRoute: typeof AuthenticatedClienteRoute
  AuthenticatedEmpresaPainelRoute: typeof AuthenticatedEmpresaPainelRoute
  AuthenticatedFuncionarioRoute: typeof AuthenticatedFuncionarioRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedRepresentanteRoute: typeof AuthenticatedRepresentanteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedClienteRoute: AuthenticatedClienteRoute,
  AuthenticatedEmpresaPainelRoute: AuthenticatedEmpresaPainelRoute,
  AuthenticatedFuncionarioRoute: AuthenticatedFuncionarioRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedRepresentanteRoute: AuthenticatedRepresentanteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CadastroRoute: CadastroRoute,
  ContatoRoute: ContatoRoute,
  EmpresaRoute: EmpresaRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  ProdutosRoute: ProdutosRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  ServicosRoute: ServicosRoute,
  SolucoesRoute: SolucoesRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
